- name: Run tasks for creating user and group "{{ ansible_username }}"
  ansible.builtin.include_role:
    name: create_user
  vars:
    username: "{{ ansible_username }}"
    ssh_public_key: " {{ ansible_ssh_public_key }} "

- name: Allow "{{ ansible_username }}" group to use sudo
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%{{ ansible_username }}"
    line: "%{{ ansible_username }} ALL=(ALL) ALL"
    validate: 'visudo -cf %s'
